### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by driplo** [driplo/gemingame#19]
Liste des tâches :
Liste des challenges / home (1)
- [x] Image + phrase d'accroche (attente)
- [x] Cacher l'alerte
- [x] Fond légèrement plus foncé
- [x] Centrer description du challenge
- [x] Remplacer les pictos

Create challenge (2)
- [x] Upload d'image *************
- [x] Choisir une couleur (new colonne)
- [x] Phrase de contexte (new colonne)

Admin (5)
- [x] Pouvoir supprimer element
- [ ] Reouvrir automatiquement à la creation d'element
- [x] Export
- [x] Picto piment à la place de l'étoile

Detail challenge (4)
- [x] Par défaut onglet Idees
- [x] Changer les pictos
- [x] Like + rebond **
- [x] Aligner à gauche le username
- [x] Cacher la page résultat
- [x] reprendre charte couleur
- [x] Img points calcul
- [x] img point info bulle recap
- [ ] ajouter picto rebonds et survol indication de quelle idée d'origine

Create ideas (3)
- [x] Drag n drop
- [x] Phrase de contexte
- [x] Changer les phrases
- [x] Boutons suivants et précédent (obliger à choisir, et gérer 1er et dernier)
- [x] 2/2 texte qui se complete automatiquement
- [x] Mettre gris jusqu'en bas
- [x] Placeholder pour le textarea
- [x] reprendre charte couleur
- [x] Idea title -> "Your product name"
